### ISSUE TITLE
How can I get this working on chrome?

### ISSUE THREAD

**Issue by Pravinakajerry** [razoo-choudhary/flaticon-premium#5]
I am not able to find downloadable file

**Comment by razoo-choudhary** [comment]
@Pravinakajerry you can find the download link in release 
https://github.com/razoo-choudhary/flaticon-premium/releases/tag/v1.1

**Comment by Pravinakajerry** [comment]
Thanks alot, this works 🤯 
Feedback: Add Package download link in readme 

It will be helpful for non techincal folks
