### ISSUE TITLE
Is there some issue today

### ISSUE THREAD

**Issue by jyothis89** [razoo-choudhary/flaticon-premium#6]
Hi, is there any issue that came up today. When i click the svg button, now the premium purchase dialog is opening.

**Comment by razoo-choudhary** [comment]
I have tried downloading it and it is working fine, maybe can you try clearing you cache or re installing the extension

![Screenshot (79)](https://user-images.githubusercontent.com/52706390/213629794-cd909959-41f5-4ca0-b96a-a896564141f8.png)

**Comment by jyothis89** [comment]
Hi @razoo-choudhary I have tried clearing the cache. I was using chrome. Also i tried installing firefox and the ectension. But same result. Will the firewall or any other settings in the system affect the extension. Yesterday i was using a different system in different network and it was working fine.

**Comment by razoo-choudhary** [comment]
@jyothis89 try this
- right click on the browser and click inspect go to network tab and refresh the page and search for flaticons.js in network tab and send me the screenshot if you can then you can contact me through telegram for better solution

**Comment by jyothis89** [comment]
![image](https://user-images.githubusercontent.com/45200954/213633540-48d586f9-5d0b-46f2-a99b-539db098e0a4.png)

**Comment by jyothis89** [comment]
Hi @razoo-choudhary How can i contact through telegram

**Comment by razoo-choudhary** [comment]
@jyothis89 i can see you are having issue while fetching the flaticons.js file contact me in telegram here 
https://t.me/+D7LOdRAmfUo4OGE1
by joining this group and send me a private message from members i will help you fix this issue

**Comment by jyothis89** [comment]
I have joined the telegram group. But cannot send any message. Can you pls help me. sorry for that.
