### ISSUE TITLE
Chrome extension does not work

### ISSUE THREAD

**Issue by EliusHHimel** [razoo-choudhary/flaticon-premium#7]
I've installed the chrome extension it says "Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details." and I tried downloading the file but it does not work.

**Comment by razoo-choudhary** [comment]
@EliusHHimel the manifest version will be updated when necessary, there should be no issue due to manifest version you can just ignore, the extension only works if you are logged in.

**Comment by EliusHHimel** [comment]
@razoo-choudhary I was logged in and I ingored the error, closed and reopened the browser ans tried again but it didn’t worked, it ask me for premium subscription.

**Comment by razoo-choudhary** [comment]
@EliusHHimel try reinstalling extesion after clearing your cache, If you still face the issue feel free to contact me in telegram.

**Comment by EliusHHimel** [comment]
it worked thanks
